# Example config.yml
git:
  showIcons: true # Shows icons in the files panel
  log:
    order: 'top-order' # Changes how commits are ordered in the log
    showGraph: always # Always shows the commit graph
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  theme:
    activeBorderColor: [255, 114, 224] # A magenta-like color
    inactiveBorderColor: [128, 128, 128] # A grey-like color
  showFileTree: true
editCommand: "nvim" # Sets your default editor
editCommandTemplate: "{{editor}} \"{{filename}}\""
